name: Nightly Build

on:   
  push: { branches: [build] }
  workflow_dispatch: {}
  schedule:
    - cron: "0 4 * * *"

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    permissions: write-all
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2021.3.14f1
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.

    steps:
      - name: Fix ownership
        run: echo ${{ secrets.USER_PASSWORD }} | sudo -S chown -R user:user .
      
      - uses: actions/checkout@v3
        with:
          ref: refs/heads/develop
          lfs: false
          
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-builder@v2.1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          
      - name: Fix ownership
        run: echo ${{ secrets.USER_PASSWORD }} | sudo -S chown -R user:user .
        
      - name: Create info file
        run: touch build/${{ matrix.targetPlatform }}/${{ github.event.repository.name }}-nightly-${{ github.ref_name }}-${{ matrix.targetPlatform }}
        
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-nightly-${{ github.ref_name }}-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          retention-days: 7
      
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: Nightly Build
          description: |
            Daily automatic & untested project build
            
            Repo [`${{ github.repository }}`](https://github.com/${{ github.repository }})
            Head Commit [`${{ github.sha }}`](https://github.com/TeamBeelding/TestRepo/commit/${{ github.sha }})
          color: 0x6726eb
          url: https://github.com/TeamBeelding/TestRepo/actions/runs/${{ github.run_id }}#artifacts
          nodetail: true
